/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import javax.swing.ImageIcon;

/**
 *
 * @author Dilhara
 */
public class Book extends javax.swing.JPanel {

    private String title;
    private String author;
    private String imagePath;

    public Book(String title, String author, String imagePath) {
        initComponents();
        this.title = title;
        this.author = author;
        this.imagePath = imagePath;
        setBookImage();
        addBookDetails();
    }

    private void setBookImage() {
        imageLabel.setIcon(new ImageIcon(getClass().getResource(this.imagePath)));
    }

    private void addBookDetails() {
        bookDetails.setText("Title: " + this.title + "\n"
                + "Author: " + this.author);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookDetails = new javax.swing.JTextArea();
        imageLabel = new javax.swing.JLabel();

        bookDetails.setEditable(false);
        bookDetails.setBackground(new java.awt.Color(255, 255, 255));
        bookDetails.setColumns(20);
        bookDetails.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        bookDetails.setLineWrap(true);
        bookDetails.setRows(3);
        bookDetails.setText("<html>\n<strong>Title:</strong> Hello \\n <strong>Author:</strong>Java\n</html>");
        bookDetails.setBorder(null);
        bookDetails.setEnabled(false);
        bookDetails.setFocusable(false);
        jScrollPane1.setViewportView(bookDetails);

        imageLabel.setBackground(new java.awt.Color(204, 255, 255));
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ai.png"))); // NOI18N
        imageLabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageLabel)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bookDetails;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
